import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Yamin Lamiri ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-[#141414] text-[#BAC4C8]">
      <body className="overflow-x-hidden min-h-screen max-w-screen ">
        {children}
      </body>
    </html>
  );
}
